/**:
  ros__parameters:
    gait:
      knee_orientation : ">>"
      pantograph_leg : false
      odom_scaler: 1.0
      max_linear_velocity_x : 0.36
      max_linear_velocity_y : 0.225
      max_angular_velocity_z : 1.18
      com_x_translation : 0.0
      swing_height : 0.02
      stance_depth : 0.0
      stance_duration : 0.35
      nominal_height : 0.1